[package]
name = "aya-log-test-macros"
version = "0.1.11-dev.0"
edition = "2018"

[dependencies]
aya-log-common = { path = "../aya-log-common" }
aya-log-parser = { path = "../aya-log-parser" }
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[lib]
proc-macro = true
